version: '3.8'

services:
  frontend:
    build:
      context: ./landing-page-front
    ports:
      - "5173:5173"   
    volumes:
      - ./landing-page-front:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev -- --host
